// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const myNfts: string;
export const close: string;
export const grid: string;
export const nft: string;
export const highlight: string;
