// @ts-nocheck
// eslint-disable
// This file is generated by create-validator-ts
import Ajv from 'ajv';
import * as apiTypes from './Locale';

export const SCHEMA = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "Hero": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "backgroundImage": {
                    "type": "string"
                },
                "backgroundColor": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "video": {
                    "type": "string"
                },
                "ps": {
                    "type": "string"
                },
                "setNumber": {
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                },
                "body": {
                    "type": "string",
                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                },
                "cta": {
                    "type": "string",
                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                },
                "action": {
                    "type": "string",
                    "enum": [
                        "ADD_TO_CALENDAR(SALE_START)",
                        "ADD_TO_CALENDAR(PRESALE_START)",
                        "SIGN_IN",
                        "MINT",
                        "GO_TO_PARAS"
                    ]
                },
                "remaining": {
                    "type": "string",
                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                }
            },
            "required": [
                "action",
                "body",
                "cta",
                "remaining",
                "title"
            ]
        },
        "RawHeroTree": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "saleClosed": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "signedOut": {
                            "type": "object",
                            "properties": {
                                "title": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "body": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "cta": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "action": {
                                    "type": "string",
                                    "enum": [
                                        "ADD_TO_CALENDAR(SALE_START)",
                                        "ADD_TO_CALENDAR(PRESALE_START)",
                                        "SIGN_IN",
                                        "MINT",
                                        "GO_TO_PARAS"
                                    ]
                                },
                                "remaining": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "backgroundImage": {
                                    "type": "string"
                                },
                                "backgroundColor": {
                                    "type": "string"
                                },
                                "image": {
                                    "type": "string"
                                },
                                "video": {
                                    "type": "string"
                                },
                                "ps": {
                                    "type": "string"
                                },
                                "setNumber": {
                                    "type": "string"
                                }
                            },
                            "additionalProperties": false
                        },
                        "signedIn": {
                            "type": "object",
                            "properties": {
                                "title": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "body": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "cta": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "action": {
                                    "type": "string",
                                    "enum": [
                                        "ADD_TO_CALENDAR(SALE_START)",
                                        "ADD_TO_CALENDAR(PRESALE_START)",
                                        "SIGN_IN",
                                        "MINT",
                                        "GO_TO_PARAS"
                                    ]
                                },
                                "remaining": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "backgroundImage": {
                                    "type": "string"
                                },
                                "backgroundColor": {
                                    "type": "string"
                                },
                                "image": {
                                    "type": "string"
                                },
                                "video": {
                                    "type": "string"
                                },
                                "ps": {
                                    "type": "string"
                                },
                                "setNumber": {
                                    "type": "string"
                                }
                            },
                            "additionalProperties": false
                        },
                        "vip": {
                            "type": "object",
                            "properties": {
                                "title": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "body": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "cta": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "action": {
                                    "type": "string",
                                    "enum": [
                                        "ADD_TO_CALENDAR(SALE_START)",
                                        "ADD_TO_CALENDAR(PRESALE_START)",
                                        "SIGN_IN",
                                        "MINT",
                                        "GO_TO_PARAS"
                                    ]
                                },
                                "remaining": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "backgroundImage": {
                                    "type": "string"
                                },
                                "backgroundColor": {
                                    "type": "string"
                                },
                                "image": {
                                    "type": "string"
                                },
                                "video": {
                                    "type": "string"
                                },
                                "ps": {
                                    "type": "string"
                                },
                                "setNumber": {
                                    "type": "string"
                                }
                            },
                            "additionalProperties": false
                        },
                        "title": {
                            "type": "string",
                            "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                        },
                        "body": {
                            "type": "string",
                            "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                        },
                        "cta": {
                            "type": "string",
                            "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                        },
                        "action": {
                            "type": "string",
                            "enum": [
                                "ADD_TO_CALENDAR(SALE_START)",
                                "ADD_TO_CALENDAR(PRESALE_START)",
                                "SIGN_IN",
                                "MINT",
                                "GO_TO_PARAS"
                            ]
                        },
                        "remaining": {
                            "type": "string",
                            "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                        },
                        "backgroundImage": {
                            "type": "string"
                        },
                        "backgroundColor": {
                            "type": "string"
                        },
                        "image": {
                            "type": "string"
                        },
                        "video": {
                            "type": "string"
                        },
                        "ps": {
                            "type": "string"
                        },
                        "setNumber": {
                            "type": "string"
                        }
                    }
                },
                "presale": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "signedOut": {
                            "type": "object",
                            "properties": {
                                "title": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "body": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "cta": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "action": {
                                    "type": "string",
                                    "enum": [
                                        "ADD_TO_CALENDAR(SALE_START)",
                                        "ADD_TO_CALENDAR(PRESALE_START)",
                                        "SIGN_IN",
                                        "MINT",
                                        "GO_TO_PARAS"
                                    ]
                                },
                                "remaining": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "backgroundImage": {
                                    "type": "string"
                                },
                                "backgroundColor": {
                                    "type": "string"
                                },
                                "image": {
                                    "type": "string"
                                },
                                "video": {
                                    "type": "string"
                                },
                                "ps": {
                                    "type": "string"
                                },
                                "setNumber": {
                                    "type": "string"
                                }
                            },
                            "additionalProperties": false
                        },
                        "signedIn": {
                            "type": "object",
                            "properties": {
                                "title": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "body": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "cta": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "action": {
                                    "type": "string",
                                    "enum": [
                                        "ADD_TO_CALENDAR(SALE_START)",
                                        "ADD_TO_CALENDAR(PRESALE_START)",
                                        "SIGN_IN",
                                        "MINT",
                                        "GO_TO_PARAS"
                                    ]
                                },
                                "remaining": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "backgroundImage": {
                                    "type": "string"
                                },
                                "backgroundColor": {
                                    "type": "string"
                                },
                                "image": {
                                    "type": "string"
                                },
                                "video": {
                                    "type": "string"
                                },
                                "ps": {
                                    "type": "string"
                                },
                                "setNumber": {
                                    "type": "string"
                                }
                            },
                            "additionalProperties": false
                        },
                        "vip": {
                            "type": "object",
                            "properties": {
                                "title": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "body": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "cta": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "action": {
                                    "type": "string",
                                    "enum": [
                                        "ADD_TO_CALENDAR(SALE_START)",
                                        "ADD_TO_CALENDAR(PRESALE_START)",
                                        "SIGN_IN",
                                        "MINT",
                                        "GO_TO_PARAS"
                                    ]
                                },
                                "remaining": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "backgroundImage": {
                                    "type": "string"
                                },
                                "backgroundColor": {
                                    "type": "string"
                                },
                                "image": {
                                    "type": "string"
                                },
                                "video": {
                                    "type": "string"
                                },
                                "ps": {
                                    "type": "string"
                                },
                                "setNumber": {
                                    "type": "string"
                                }
                            },
                            "additionalProperties": false
                        },
                        "title": {
                            "type": "string",
                            "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                        },
                        "body": {
                            "type": "string",
                            "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                        },
                        "cta": {
                            "type": "string",
                            "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                        },
                        "action": {
                            "type": "string",
                            "enum": [
                                "ADD_TO_CALENDAR(SALE_START)",
                                "ADD_TO_CALENDAR(PRESALE_START)",
                                "SIGN_IN",
                                "MINT",
                                "GO_TO_PARAS"
                            ]
                        },
                        "remaining": {
                            "type": "string",
                            "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                        },
                        "backgroundImage": {
                            "type": "string"
                        },
                        "backgroundColor": {
                            "type": "string"
                        },
                        "image": {
                            "type": "string"
                        },
                        "video": {
                            "type": "string"
                        },
                        "ps": {
                            "type": "string"
                        },
                        "setNumber": {
                            "type": "string"
                        }
                    }
                },
                "saleOpen": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "signedOut": {
                            "type": "object",
                            "properties": {
                                "title": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "body": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "cta": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "action": {
                                    "type": "string",
                                    "enum": [
                                        "ADD_TO_CALENDAR(SALE_START)",
                                        "ADD_TO_CALENDAR(PRESALE_START)",
                                        "SIGN_IN",
                                        "MINT",
                                        "GO_TO_PARAS"
                                    ]
                                },
                                "remaining": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "backgroundImage": {
                                    "type": "string"
                                },
                                "backgroundColor": {
                                    "type": "string"
                                },
                                "image": {
                                    "type": "string"
                                },
                                "video": {
                                    "type": "string"
                                },
                                "ps": {
                                    "type": "string"
                                },
                                "setNumber": {
                                    "type": "string"
                                }
                            },
                            "additionalProperties": false
                        },
                        "signedIn": {
                            "type": "object",
                            "properties": {
                                "title": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "body": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "cta": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "action": {
                                    "type": "string",
                                    "enum": [
                                        "ADD_TO_CALENDAR(SALE_START)",
                                        "ADD_TO_CALENDAR(PRESALE_START)",
                                        "SIGN_IN",
                                        "MINT",
                                        "GO_TO_PARAS"
                                    ]
                                },
                                "remaining": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "backgroundImage": {
                                    "type": "string"
                                },
                                "backgroundColor": {
                                    "type": "string"
                                },
                                "image": {
                                    "type": "string"
                                },
                                "video": {
                                    "type": "string"
                                },
                                "ps": {
                                    "type": "string"
                                },
                                "setNumber": {
                                    "type": "string"
                                }
                            },
                            "additionalProperties": false
                        },
                        "vip": {
                            "type": "object",
                            "properties": {
                                "title": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "body": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "cta": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "action": {
                                    "type": "string",
                                    "enum": [
                                        "ADD_TO_CALENDAR(SALE_START)",
                                        "ADD_TO_CALENDAR(PRESALE_START)",
                                        "SIGN_IN",
                                        "MINT",
                                        "GO_TO_PARAS"
                                    ]
                                },
                                "remaining": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "backgroundImage": {
                                    "type": "string"
                                },
                                "backgroundColor": {
                                    "type": "string"
                                },
                                "image": {
                                    "type": "string"
                                },
                                "video": {
                                    "type": "string"
                                },
                                "ps": {
                                    "type": "string"
                                },
                                "setNumber": {
                                    "type": "string"
                                }
                            },
                            "additionalProperties": false
                        },
                        "title": {
                            "type": "string",
                            "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                        },
                        "body": {
                            "type": "string",
                            "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                        },
                        "cta": {
                            "type": "string",
                            "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                        },
                        "action": {
                            "type": "string",
                            "enum": [
                                "ADD_TO_CALENDAR(SALE_START)",
                                "ADD_TO_CALENDAR(PRESALE_START)",
                                "SIGN_IN",
                                "MINT",
                                "GO_TO_PARAS"
                            ]
                        },
                        "remaining": {
                            "type": "string",
                            "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                        },
                        "backgroundImage": {
                            "type": "string"
                        },
                        "backgroundColor": {
                            "type": "string"
                        },
                        "image": {
                            "type": "string"
                        },
                        "video": {
                            "type": "string"
                        },
                        "ps": {
                            "type": "string"
                        },
                        "setNumber": {
                            "type": "string"
                        }
                    }
                },
                "allSold": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "signedOut": {
                            "type": "object",
                            "properties": {
                                "title": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "body": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "cta": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "action": {
                                    "type": "string",
                                    "enum": [
                                        "ADD_TO_CALENDAR(SALE_START)",
                                        "ADD_TO_CALENDAR(PRESALE_START)",
                                        "SIGN_IN",
                                        "MINT",
                                        "GO_TO_PARAS"
                                    ]
                                },
                                "remaining": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "backgroundImage": {
                                    "type": "string"
                                },
                                "backgroundColor": {
                                    "type": "string"
                                },
                                "image": {
                                    "type": "string"
                                },
                                "video": {
                                    "type": "string"
                                },
                                "ps": {
                                    "type": "string"
                                },
                                "setNumber": {
                                    "type": "string"
                                }
                            },
                            "additionalProperties": false
                        },
                        "signedIn": {
                            "type": "object",
                            "properties": {
                                "title": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "body": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "cta": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "action": {
                                    "type": "string",
                                    "enum": [
                                        "ADD_TO_CALENDAR(SALE_START)",
                                        "ADD_TO_CALENDAR(PRESALE_START)",
                                        "SIGN_IN",
                                        "MINT",
                                        "GO_TO_PARAS"
                                    ]
                                },
                                "remaining": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "backgroundImage": {
                                    "type": "string"
                                },
                                "backgroundColor": {
                                    "type": "string"
                                },
                                "image": {
                                    "type": "string"
                                },
                                "video": {
                                    "type": "string"
                                },
                                "ps": {
                                    "type": "string"
                                },
                                "setNumber": {
                                    "type": "string"
                                }
                            },
                            "additionalProperties": false
                        },
                        "vip": {
                            "type": "object",
                            "properties": {
                                "title": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "body": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "cta": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "action": {
                                    "type": "string",
                                    "enum": [
                                        "ADD_TO_CALENDAR(SALE_START)",
                                        "ADD_TO_CALENDAR(PRESALE_START)",
                                        "SIGN_IN",
                                        "MINT",
                                        "GO_TO_PARAS"
                                    ]
                                },
                                "remaining": {
                                    "type": "string",
                                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                                },
                                "backgroundImage": {
                                    "type": "string"
                                },
                                "backgroundColor": {
                                    "type": "string"
                                },
                                "image": {
                                    "type": "string"
                                },
                                "video": {
                                    "type": "string"
                                },
                                "ps": {
                                    "type": "string"
                                },
                                "setNumber": {
                                    "type": "string"
                                }
                            },
                            "additionalProperties": false
                        },
                        "title": {
                            "type": "string",
                            "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                        },
                        "body": {
                            "type": "string",
                            "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                        },
                        "cta": {
                            "type": "string",
                            "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                        },
                        "action": {
                            "type": "string",
                            "enum": [
                                "ADD_TO_CALENDAR(SALE_START)",
                                "ADD_TO_CALENDAR(PRESALE_START)",
                                "SIGN_IN",
                                "MINT",
                                "GO_TO_PARAS"
                            ]
                        },
                        "remaining": {
                            "type": "string",
                            "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                        },
                        "backgroundImage": {
                            "type": "string"
                        },
                        "backgroundColor": {
                            "type": "string"
                        },
                        "image": {
                            "type": "string"
                        },
                        "video": {
                            "type": "string"
                        },
                        "ps": {
                            "type": "string"
                        },
                        "setNumber": {
                            "type": "string"
                        }
                    }
                },
                "title": {
                    "type": "string",
                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                },
                "body": {
                    "type": "string",
                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                },
                "cta": {
                    "type": "string",
                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                },
                "action": {
                    "type": "string",
                    "enum": [
                        "ADD_TO_CALENDAR(SALE_START)",
                        "ADD_TO_CALENDAR(PRESALE_START)",
                        "SIGN_IN",
                        "MINT",
                        "GO_TO_PARAS"
                    ]
                },
                "remaining": {
                    "type": "string",
                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                },
                "backgroundImage": {
                    "type": "string"
                },
                "backgroundColor": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "video": {
                    "type": "string"
                },
                "ps": {
                    "type": "string"
                },
                "setNumber": {
                    "type": "string"
                }
            }
        },
        "SectionI18n": {
            "type": "object",
            "properties": {
                "text": {
                    "type": "string",
                    "description": "Commonmark-formatted markdown. @see https://remarkjs.github.io/react-markdown/"
                },
                "image": {
                    "type": "string"
                },
                "video": {
                    "type": "string"
                },
                "backgroundImage": {
                    "type": "string"
                },
                "backgroundColor": {
                    "type": "string"
                },
                "className": {
                    "type": "string"
                },
                "blocks": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "image": {
                                "type": "string"
                            },
                            "text": {
                                "type": "string"
                            },
                            "linkTo": {
                                "type": "string"
                            }
                        },
                        "additionalProperties": false
                    }
                }
            },
            "required": [
                "text"
            ],
            "additionalProperties": false
        },
        "Locale": {
            "type": "object",
            "properties": {
                "viewIn": {
                    "type": "string"
                },
                "langPicker": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "calendarEvent": {
                    "type": "string"
                },
                "connectWallet": {
                    "type": "string"
                },
                "signOut": {
                    "type": "string"
                },
                "new": {
                    "type": "string"
                },
                "myNFTs": {
                    "type": "string"
                },
                "nextNFT": {
                    "type": "string"
                },
                "prevNFT": {
                    "type": "string"
                },
                "close": {
                    "type": "string"
                },
                "zoomIn": {
                    "type": "string"
                },
                "zoomOut": {
                    "type": "string"
                },
                "hero": {
                    "$ref": "#/definitions/RawHeroTree"
                },
                "extraSections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/SectionI18n"
                    }
                }
            },
            "required": [
                "viewIn",
                "langPicker",
                "title",
                "description",
                "calendarEvent",
                "connectWallet",
                "signOut",
                "new",
                "myNFTs",
                "nextNFT",
                "prevNFT",
                "close",
                "zoomIn",
                "zoomOut",
                "hero"
            ],
            "additionalProperties": false
        }
    }
};
const ajv = new Ajv({ removeAdditional: true }).addSchema(SCHEMA, "SCHEMA");
export function validateHero(payload: unknown): apiTypes.Hero {
  /** Schema is defined in {@link SCHEMA.definitions.Hero } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/Hero");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid Hero: ' + ajv.errorsText(validator.errors, {dataVar: "Hero"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isHero(payload: unknown): payload is apiTypes.Hero {
  try {
    validateHero(payload);
    return true;
  } catch (error) {
    return false;
  }
}

export function validateRawHeroTree(payload: unknown): apiTypes.RawHeroTree {
  /** Schema is defined in {@link SCHEMA.definitions.RawHeroTree } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/RawHeroTree");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid RawHeroTree: ' + ajv.errorsText(validator.errors, {dataVar: "RawHeroTree"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isRawHeroTree(payload: unknown): payload is apiTypes.RawHeroTree {
  try {
    validateRawHeroTree(payload);
    return true;
  } catch (error) {
    return false;
  }
}

export function validateSectionI18n(payload: unknown): apiTypes.SectionI18n {
  /** Schema is defined in {@link SCHEMA.definitions.SectionI18n } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/SectionI18n");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid SectionI18n: ' + ajv.errorsText(validator.errors, {dataVar: "SectionI18n"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isSectionI18n(payload: unknown): payload is apiTypes.SectionI18n {
  try {
    validateSectionI18n(payload);
    return true;
  } catch (error) {
    return false;
  }
}

export function validateLocale(payload: unknown): apiTypes.Locale {
  /** Schema is defined in {@link SCHEMA.definitions.Locale } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/Locale");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid Locale: ' + ajv.errorsText(validator.errors, {dataVar: "Locale"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isLocale(payload: unknown): payload is apiTypes.Locale {
  try {
    validateLocale(payload);
    return true;
  } catch (error) {
    return false;
  }
}
