// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const content: string;
export const lead: string;
export const remaining: string;
export const cta: string;
export const labelWrap: string;
export const label: string;
