// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const bg: string;
export const content: string;
export const social: string;
export const actions: string;
export const button: string;
