// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const root: string;
export const track: string;
export const range: string;
export const thumb: string;
